### ISSUE TITLE
v.3.2.0 Edits

### ISSUE THREAD

**Issue by KeyJoo** [KeyJoo/baraban16#65]
# v.3.2.0 Edits

- [x] add legacy from 3.1.0 hosting
- [x] structure files
- [x] add blocks
- [x] add modifications
- [x] clean code

`css/main.css` 
  - Add 
```css
p {
   padding-top: 10px;
}
```
